# Generated by Django 5.1.2 on 2024-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Votos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
